name = input("Enter First Name: ")
print(" First Name:", name)
last = input("Enter Last Name: ")
print(" Last Name:", last)
middle = input("Enter Middle Name: ")
print("Middle Name:", middle)
birthday = input("Enter Birthday: ")
print("Birtday:", birthday)
gender = input("Enter Gender: ")
print("Gender:", gender)
address = input("Enter Address: ")
print("Address:", address)
Course = input("Enter Course: ")
print("Course:", Course)
Year = input("Enter Year level: ")
print("Year level:", Year)